# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GuiGraphParos.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(911, 620)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.cboxTabParos1PortParos1 = QtWidgets.QComboBox(self.centralwidget)
        self.cboxTabParos1PortParos1.setObjectName("cboxTabParos1PortParos1")
        self.horizontalLayout_6.addWidget(self.cboxTabParos1PortParos1)
        self.lblTabParos1PortSelected = QtWidgets.QLabel(self.centralwidget)
        self.lblTabParos1PortSelected.setObjectName("lblTabParos1PortSelected")
        self.horizontalLayout_6.addWidget(self.lblTabParos1PortSelected)
        self.sboxTabParos1NPoints = QtWidgets.QSpinBox(self.centralwidget)
        self.sboxTabParos1NPoints.setMinimum(1)
        self.sboxTabParos1NPoints.setMaximum(200)
        self.sboxTabParos1NPoints.setProperty("value", 10)
        self.sboxTabParos1NPoints.setObjectName("sboxTabParos1NPoints")
        self.horizontalLayout_6.addWidget(self.sboxTabParos1NPoints)
        self.lblTabParos1NPointsSelected = QtWidgets.QLabel(self.centralwidget)
        self.lblTabParos1NPointsSelected.setObjectName("lblTabParos1NPointsSelected")
        self.horizontalLayout_6.addWidget(self.lblTabParos1NPointsSelected)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lineTabParos1Comment = QtWidgets.QLineEdit(self.centralwidget)
        self.lineTabParos1Comment.setObjectName("lineTabParos1Comment")
        self.horizontalLayout_5.addWidget(self.lineTabParos1Comment)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.btnTabParos1Start = QtWidgets.QPushButton(self.centralwidget)
        self.btnTabParos1Start.setObjectName("btnTabParos1Start")
        self.horizontalLayout_5.addWidget(self.btnTabParos1Start)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.lblTabParos1ActualValue = QtWidgets.QLabel(self.centralwidget)
        self.lblTabParos1ActualValue.setObjectName("lblTabParos1ActualValue")
        self.horizontalLayout_3.addWidget(self.lblTabParos1ActualValue)
        self.lblTabParos_mbar = QtWidgets.QLabel(self.centralwidget)
        self.lblTabParos_mbar.setObjectName("lblTabParos_mbar")
        self.horizontalLayout_3.addWidget(self.lblTabParos_mbar)
        self.sboxTabParos1TextSize = QtWidgets.QSpinBox(self.centralwidget)
        self.sboxTabParos1TextSize.setMinimum(20)
        self.sboxTabParos1TextSize.setMaximum(100)
        self.sboxTabParos1TextSize.setObjectName("sboxTabParos1TextSize")
        self.horizontalLayout_3.addWidget(self.sboxTabParos1TextSize)
        self.lblTabParos_fixed = QtWidgets.QLabel(self.centralwidget)
        self.lblTabParos_fixed.setObjectName("lblTabParos_fixed")
        self.horizontalLayout_3.addWidget(self.lblTabParos_fixed)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.plotTabParos1RawParos1 = PlotWidget(self.centralwidget)
        self.plotTabParos1RawParos1.setObjectName("plotTabParos1RawParos1")
        self.horizontalLayout.addWidget(self.plotTabParos1RawParos1)
        self.plotTabParos1NetParos1 = PlotWidget(self.centralwidget)
        self.plotTabParos1NetParos1.setObjectName("plotTabParos1NetParos1")
        self.horizontalLayout.addWidget(self.plotTabParos1NetParos1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btnTabParos1Stop = QtWidgets.QPushButton(self.centralwidget)
        self.btnTabParos1Stop.setObjectName("btnTabParos1Stop")
        self.horizontalLayout_7.addWidget(self.btnTabParos1Stop)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.btnTabParos1Close = QtWidgets.QPushButton(self.centralwidget)
        self.btnTabParos1Close.setObjectName("btnTabParos1Close")
        self.horizontalLayout_7.addWidget(self.btnTabParos1Close)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 911, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblTabParos1PortSelected.setText(_translate("MainWindow", "TextLabel"))
        self.lblTabParos1NPointsSelected.setText(_translate("MainWindow", "TextLabel"))
        self.lineTabParos1Comment.setText(_translate("MainWindow", "ComentParosFile"))
        self.label_6.setText(_translate("MainWindow", " -  The data will be save on a TXT file - "))
        self.btnTabParos1Start.setText(_translate("MainWindow", "START"))
        self.lblTabParos1ActualValue.setText(_translate("MainWindow", "0"))
        self.lblTabParos_mbar.setText(_translate("MainWindow", " mbar "))
        self.lblTabParos_fixed.setText(_translate("MainWindow", " Increase text size (max: 100)"))
        self.label.setText(_translate("MainWindow", "- -"))
        self.label_3.setText(_translate("MainWindow", "- -"))
        self.label_2.setText(_translate("MainWindow", "- -"))
        self.label_4.setText(_translate("MainWindow", "- -"))
        self.btnTabParos1Stop.setText(_translate("MainWindow", "STOP"))
        self.btnTabParos1Close.setText(_translate("MainWindow", "CLOSE"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))

from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

